# Generated by Django 4.2.16 on 2024-09-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(help_text='Background color in HEX format (e.g., #FFFFFF)', max_length=7, verbose_name='Background Color')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Background Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Subtitle')),
                ('column_number', models.PositiveIntegerField()),
                ('column_content_1_image', models.ImageField(blank=True, null=True, upload_to='column_images/')),
                ('column_content_1_text', models.TextField(blank=True, null=True)),
                ('column_content_2_image', models.ImageField(blank=True, null=True, upload_to='column_images/')),
                ('column_content_2_text', models.TextField(blank=True, null=True)),
                ('column_content_3_image', models.ImageField(blank=True, null=True, upload_to='column_images/')),
                ('column_content_3_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
