# Generated by Django 4.2.16 on 2024-09-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_page_dark_mode_page_effect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='column_number',
            field=models.IntegerField(),
        ),
    ]
