# Generated by Django 4.2.16 on 2024-09-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_page_column_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='column_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
